module.exports = {
    IPC_LOAD_FILE: 'IPC_LOAD_FILE',
    IPC_LOAD_FILE_REPLY: 'IPC_LOAD_FILE_REPLY',
    IPC_SELECT_FILE: 'IPC_SELECT_FILE',
    IPC_SELECT_DIR: 'IPC_SELECT_DIR',
    IPC_LOAD_DIR_REPLY: 'IPC_LOAD_DIR_REPLY',
    IPC_SAVE_FILE: 'IPC_SAVE_FILE',
    IPC_SAVE_FILE_REPLY: 'IPC_SAVE_FILE_REPLY',
    IPC_LOAD_HISTORY: 'IPC_LOAD_HISTORY',
    IPC_LOAD_HISTORY_REPLY: 'IPC_LOAD_HISTORY_REPLY'
}
